apiVersion: v1
kind: PersistentVolume
metadata:
  name: chashi-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: chashicsi
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: chashicsi
    volumeHandle: chashi-blob-volume
