apiVersion: v1
kind: Pod
metadata:
  name: blob-storage-test-pod
spec:
  containers:
  - name: blob-storage-container
    image: ubuntu:20.04
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 3600; done"]
    volumeMounts:
    - name: blob-storage-volume
      mountPath: /mnt/blob
  volumes:
  - name: blob-storage-volume
    persistentVolumeClaim:
      claimName: chashi-pvc
